MusicDatabase/Controllers/DatabaseController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MusicDatabase.Models;
using MusicDatabase.Data;
using System.Security.Cryptography;
using System.Text;
using System.Net.Sockets;

namespace MusicDatabase.Controllers;

public class DatabaseController : Controller
{
    private string ToHex(byte[] bytes, bool upperCase)
    {
        StringBuilder result = new StringBuilder(bytes.Length * 2);
        for (int i = 0; i < bytes.Length; i++)
            result.Append(bytes[i].ToString(upperCase ? "X2" : "x2"));
        return result.ToString();
    }

    private byte[] GenerateToken(byte[] data)
    {
        using (var sha256 = SHA256.Create())
        {
            return sha256.ComputeHash(data);
        }
    }
    private readonly ILogger<HomeController> _logger;

    protected private MusicContext database = new MusicContext();

    public DatabaseController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }
    [HttpGet]
    public IActionResult Add()
    {
        return View();
    }
    [HttpPost]
    // [ValidateAntiForgeryToken]
    public IActionResult Add(string SongName, string SongArtist, string SongAlbum, string SongReleased, string SongThumbnail, string SongURL)
    {
        SongEntry song = new SongEntry();
        song.SongName = SongName;
        song.SongArtist = SongArtist;
        song.SongAlbum = SongAlbum;
        song.SongReleased = SongReleased;
        song.SongThumbnail = SongThumbnail;
        song.SongURL = SongURL;
        song.SongEntryId = Convert.ToHexString(SHA256.HashData(Encoding.ASCII.GetBytes(SongName)));
        database.Add(song);
        database.SaveChanges();
        return View();
    }

    [HttpGet]
    public IActionResult Edit(string? Id)
    {
        if (Id != null && database.songEntries != null)
        {
            var songEntry = database.songEntries.Find(Id);
            return View(songEntry);
        }
        else
        {
            return Redirect("/Database/List");
        }
    }
    [HttpPost]
    public IActionResult Edit(string SongID, string SongName, string SongArtist, string SongAlbum, string SongReleased, string SongThumbnail, string SongURL)
    {
        if (database.songEntries != null)
        {
            var song = database.songEntries.Find(SongID);
            if (song != null)
            {
                song.SongName = SongName;
                song.SongArtist = SongArtist;
                song.SongAlbum = SongAlbum;
                song.SongReleased = SongReleased;
                song.SongURL = SongURL;
                song.SongThumbnail = SongThumbnail;
                database.SaveChanges();
            }
            return Redirect("/Database/Edit/" + SongID);
        }
        return Redirect("/Database/Edit/" + SongID);
    }

    public IActionResult List()
    {
        if (database.songEntries != null)
        {
            var songs = database.songEntries.ToArray();
            SongListModel model = new SongListModel();
            model.SongList = songs;

            return View(model);
        }
        return View();
    }

    public IActionResult Delete(string? id)
    {
        if (id != null)
        {
            if (database.songEntries != null)
            {
                var song = database.songEntries.Find(id);
                if (song != null)
                {
                    database.songEntries.Remove(song);
                    database.SaveChanges();
                }
            }
        }
        return Redirect("/Database/List");
    }

    public IActionResult Download(string? Id)
    {
        #pragma warning disable

        string INVALID_CODE = "100";
        string START_DOWNLOAD = "101";
        string END_DOWNLOAD = "102";
        string URL_START = "103";
        string URL_END = "104";
        string URL_OK = "105";
        string URL_ERROR = "106";
        string HASH_START = "107";
        string HASH_END = "108";
        string HASH_OK = "109";
        string HASH_ERROR = "110";
        string DOWNLOAD_MEDIA = "111";
        string DOWNLOAD_COMPLETE = "112";
        string DOWNLOAD_ERROR = "113";
        string TOKEN_SUCCESS = "114";
        string TOKEN_ERROR = "115";

        #pragma warning restore
        if (Id == null)
        {
            return Content("<h1>Please pass ID</h1>");
        }
        if (database.songEntries != null)
        {
            SongEntry? song = database.songEntries.Find(Id);
            try
            {
                if (database.songEntries != null)
                {
                    var server = new TcpClient(AddressFamily.InterNetwork);
                    server.Connect("localhost", 8731);
                    var stream = server.GetStream();

                    byte[] code = new byte[3];

                    byte[] serverToken = new byte[64];
                    stream.Read(serverToken, 0, 64);
                    byte[] clientToken = Encoding.ASCII.GetBytes(ToHex(GenerateToken(serverToken), false));
                    stream.Write(clientToken);

                    stream.Read(code, 0, 3);

                    if (Encoding.ASCII.GetString(code) != TOKEN_SUCCESS)
                    {
                        stream.Close();
                        server.Close();
                        server.Dispose();
                        return Content("<h1>ERROR OCCURED</h1>\n<h2>Invalid Token</h2>", "text/html");
                    }
                    stream.Write(Encoding.ASCII.GetBytes(START_DOWNLOAD));

                    if (song != null)
                    {

                        if (song.SongEntryId != null && song.SongURL != null)
                        {
                            Console.WriteLine("Name: " + song.SongName);
                            Console.WriteLine("URL: " + song.SongURL);

                            stream.Write(Encoding.ASCII.GetBytes(URL_START));
                            Thread.Sleep(1000);

                            stream.Write(Encoding.ASCII.GetBytes(song.SongURL));
                            Thread.Sleep(1000);

                            stream.Write(Encoding.ASCII.GetBytes(URL_END));
                            Thread.Sleep(1000);

                            stream.Read(code, 0, 3);
                            Thread.Sleep(1000);

                            if (Encoding.ASCII.GetString(code) == URL_OK)
                            {
                                stream.Write(Encoding.ASCII.GetBytes(HASH_START));
                                Thread.Sleep(1000);

                                stream.Write(Encoding.ASCII.GetBytes(song.SongEntryId));
                                Thread.Sleep(1000);

                                stream.Write(Encoding.ASCII.GetBytes(HASH_END));
                                Thread.Sleep(1000);

                                stream.Read(code, 0, 3);
                                Thread.Sleep(1000);

                                if (Encoding.ASCII.GetString(code) == HASH_OK)
                                {
                                    stream.Write(Encoding.ASCII.GetBytes(DOWNLOAD_MEDIA));
                                    Thread.Sleep(1000);
                                    stream.Read(code, 0, 3);
                                    Thread.Sleep(1000);
                                    if (Encoding.ASCII.GetString(code) == DOWNLOAD_COMPLETE)
                                    {
                                        Console.WriteLine("DOWNLOADED: " + song.SongURL);
                                        stream.Write(Encoding.ASCII.GetBytes(END_DOWNLOAD));
                                        return Content("<h1>DOWNLOADED SUCCESSFULLY</h1>", "text/html");
                                    }
                                    else if (Encoding.ASCII.GetString(code) == DOWNLOAD_ERROR)
                                    {
                                        Console.WriteLine("ERROR DOWNLOADING: " + song.SongURL);
                                        stream.Write(Encoding.ASCII.GetBytes(END_DOWNLOAD));
                                        return Content("<h1>DOWNLOAD FAILED</h1>", "text/html");
                                    }
                                }
                            }
                        }
                    }
                    stream.Close();
                    server.Close();
                    server.Dispose();
                }
            }
            catch (System.Exception e)
            {
                Console.WriteLine(e);
                return Content($"<h1>ERROR OCCURED</h1>\n<h2>{e.Message}</h2>", "text/html");
            }
        }
        return Content("ERROR");
    }

    public IActionResult Search(string? searchTerm)
    {
        SongListModel songList = new SongListModel();
        int count = 0;
        SongEntry[] results = { };

        if (searchTerm == "" || searchTerm == null)
        {
            return Content("");
        }else if(searchTerm == "$ALL$")
        {
            songList.SongList = database.songEntries.ToArray();
            return View(songList);
        }

        if (database.songEntries != null)
        {
            foreach (var song in database.songEntries)
            {
                if (song != null)
                {
                    if (song.SongName != null)
                        if (song.SongName.ToLower().Contains(searchTerm.ToLower()))
                        {
                            results = results.Append<SongEntry>(song).ToArray();
                            count++;
                            continue;
                        }
                    if (song.SongAlbum != null)
                    {
                        if (song.SongAlbum.ToLower().Contains(searchTerm.ToLower()))
                        {
                            results = results.Append<SongEntry>(song).ToArray();

MusicDatabase/Views/Database/Add.cshtml
@{
    ViewData["Title"] = "Add";
}

<div style="padding: 2em 4em;">
    <p class="display-6 text-center">Add Song Entry</p>
    <form action="add" method="post">
        @* @Html.AntiForgeryToken() *@
        <div class="mb-3">
            <label for="SongName" class="form-label">Song Name</label>
            <input type="text" class="form-control" id="SongName" name="SongName" placeholder="On My Way" required>
        </div>

        <div class="mb-3">
            <label for="SongArtist" class="form-label">Song Artist</label>
            <input type="text" class="form-control" id="SongArtist" name="SongArtist" placeholder="Alan Walker">
        </div>

        <div class="mb-3">
            <label for="SongAlbum" class="form-label">Song Album</label>
            <input type="text" class="form-control" id="SongAlbum" name="SongAlbum" placeholder="Live Fast">
        </div>

        <div class="mb-3">
            <label for="SongReleased" class="form-label">Song Release Date</label>
            <input type="text" class="form-control" id="SongReleased" name="SongReleased" placeholder="2019">
        </div>

        <div class="mb-3">
            <label for="SongThumbnail" class="form-label">Song Thumbnail</label>
            <input type="text" class="form-control" id="SongThumbnail" name="SongThumbnail" placeholder="https://cdn.images.com/img?id=images.jpeg">
        </div>

        <div class="mb-3">
            <label for="SongURL" class="form-label">Song URL</label>
            <input type="text" class="form-control" id="SongURL" name="SongURL" placeholder="https://music.youtube.com/watch?v=">
        </div>

        <button type="submit" class="btn btn-primary">Add Song</button>

    </form>
<div>

MusicDatabase/Views/Database/Edit.cshtml
@model MusicDatabase.Models.SongEntry;

@{
    ViewData["Title"] = "Edit";
}

@if (Model != null)
{   
    <div style="padding:2em 4em;"> 
        <p class="display-6 text-center">Edit Song Entry</p>

        <form action="Edit" method="post">
            <div class="mb-3">
                <label for="SongID" class="form-label">Song ID</label>
                <input type="text" value="@Model.SongEntryId" class="form-control" id="SongID" name="SongID" placeholder="" readonly>
            </div>

            <div class="mb-3">
                <label for="SongName" class="form-label">Song Name</label>
                <input type="text" value="@Model.SongName" class="form-control" id="SongName" name="SongName" placeholder="On My Way">
            </div>

            <div class="mb-3">
                <label for="SongArtist" class="form-label">Song Artist</label>
                <input type="text" value="@Model.SongArtist" class="form-control" id="SongArtist" name="SongArtist" placeholder="Alan Walker">
            </div>

            <div class="mb-3">
                <label for="SongAlbum" class="form-label">Song Album</label>
                <input type="text" value="@Model.SongAlbum" class="form-control" id="SongAlbum" name="SongAlbum" placeholder="Live Fast">
            </div>

            <div class="mb-3">
                <label for="SongReleased" class="form-label">Song Release Date</label>
                <input type="text" value="@Model.SongReleased" class="form-control" id="SongReleased" name="SongReleased" placeholder="2019">
            </div>

            <div class="mb-3">
                <label for="SongThumbnail" class="form-label">Song Thumbnail</label>
                <input type="text" value="@Model.SongThumbnail" class="form-control" id="SongThumbnail" name="SongThumbnail" placeholder="https://cdn.images.com/img?id=images.jpeg">
            </div>

            <div class="mb-3">
                <label for="SongURL" class="form-label">Song URL</label>
                <input type="text" value="@Model.SongURL" class="form-control" id="SongURL" name="SongURL" placeholder="https://music.youtube.com/watch?v=">
            </div>

            <button type="submit" class="btn btn-primary">Save Song</button>
            <a asp-controller="Database" asp-action="Download" asp-route-id="@Model.SongEntryId" type="butt on" class="btn btn-primary">Download Song</a>
            <a asp-controller="Database" asp-action="Delete" asp-route-id="@Model.SongEntryId" class="  btn btn-danger">Delete Song</a>

        </form>
    </div>
}else{
    <p class="display-6 text-center text-danger">Please Give Valid SongID</p>
}

MusicDatabase/Views/Database/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<div class="text-center">
    <h1 class="display-4">Welcome MusicDatabase Index</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MusicDatabase/Views/Database/List.cshtml
@model MusicDatabase.Models.SongListModel;
@{
    ViewData["Title"] = "View"; 
    int counter = 0;
}
<link rel="stylesheet" type="text/css" href="~/css/songlist.css">
<p class="heading">Songs</p>
<div class="listContainer">
    @{
            if (Model.SongList != null)
            {
                foreach (var song in Model.SongList)
                {
                    counter++;
                <div class="songItem">
                    <div>
                        @* <p>@counter</p> *@
                        <div>
                            <p class="songName">@song.SongName</p>
                            <p class="songArtist">@song.SongArtist</p>
                        </div>
                        <!-- <p class="songAlbum">@song.SongAlbum</p> -->
                    </div>
                    <div>
                        <!-- <a class="btn btn-primary" asp-controller="Play" asp-action="Index" asp-route-id="@song.SongEntryId">Play</a> -->
                        <a class="btn btn-primary" href="/Play?mid=@song.SongEntryId">Play</a>
                        <a class="btn btn-primary" asp-controller="Database" asp-action="Edit" asp-route-id="@song.SongEntryId">Edit</a>
                        <a class="btn btn-primary" asp-controller="Database" asp-action="Delete" asp-route-id="@song.SongEntryId">Delete</a>
                    </div>
                </div>
                }
            }
        }
</div>
@if (counter == 0)
{
    <p class="display-6 text-center text-alert">Song Database is Empty</p>
}

MusicDatabase/Views/Database/Search.cshtml
@model MusicDatabase.Models.SongListModel;
@{
    ViewData["Title"] = "Search";
    int counter = 0;
}

<table class="table">
    <thead>
        <tr>
            <th scope="col">No.</th>
            <th scope="col">Song Name</th>
            <th scope="col">Song Artist</th>
            <th scope="col">Song Album</th>
            <th scope="col">Released</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        @{
            if (Model.SongList != null)
            {
                foreach (var song in Model.SongList)
                {
                    counter++;
                    <tr>
                        <th scope="row">@counter</th>
                        <td>@song.SongName</td>
                        <td>@song.SongArtist</td>
                        <td>@song.SongAlbum</td>
                        <td>@song.SongReleased</td>
                        <td>
                            <a class="link-primary p-1" href="/Play?mid=@song.SongEntryId">Play</a>
                            <a class="link-primary p-1" asp-controller="Database" asp-action="Edit" asp-route-id="@song.SongEntryId">Edit</a>
                            <a class="link-primary p-1" asp-controller="Database" asp-action="Delete" asp-route-id="@song.SongEntryId">Delete</a>
                        </td>
                    </tr>
                }
            }
        }
    </tbody>
</table>
@if (counter == 0)
{
    <p class="display-6 text-center text-alert">Song Database is Empty</p>
}